<?php
$LOCAL_LANG = Array(
    'default' => Array(
        'ubleipzigbooking.pi_flexform.sheetDisplayOptions' => 'display options',
        'ubleipzigbooking.pi_flexform.sheetTemplateOptions' => 'template options',
        'ubleipzigbooking.pi_flexform.displayMode.label' => 'display mode',
        'ubleipzigbooking.pi_flexform.monthView.label' => 'month view',
        'ubleipzigbooking.pi_flexform.weekView.label' => 'week view',
        'ubleipzigbooking.pi_flexform.includejQuery.label' => 'include jQuery library',
        'ubleipzigbooking.pi_flexform.enableQuarterHourBooking.label' => 'enable quarter hour booking',
        'ubleipzigbooking.pi_flexform.maxBookingsPerDay.label' => 'max. bookings per day',
        'ubleipzigbooking.pi_flexform.limitPreviewToDays.label' => 'Limit preview to n days in future',
        'ubleipzigbooking.pi_flexform.limitBookingToDays.label' => 'Limit booking to n days in future',
        'ubleipzigbooking.pi_flexform.enableFeUserMail.label' => 'Enable FE user mail',
        'ubleipzigbooking.pi_flexform.mailSubject.label' => 'Mail subject',
        'ubleipzigbooking.pi_flexform.mailFromName.label' => 'Mail from name',
        'ubleipzigbooking.pi_flexform.mailFrom.label' => 'Mail from',
        'ubleipzigbooking.pi_flexform.mailAttachment.label' => 'Mail attachment',
        'ubleipzigbooking.pi_flexform.offDutyTimeBegin.label' => 'Off-duty days start',
        'ubleipzigbooking.pi_flexform.offDutyTimeEnd.label' => 'Off-duty days end',
        'ubleipzigbooking.pi_flexform.templateFile.label' => 'template file',
        'ubleipzigbooking.pi_flexform.cssFile.label' => 'CSS file',
    ) ,
    'de' => Array(
        'ubleipzigbooking.pi_flexform.sheetDisplayOptions' => 'Anzeige-Optionen',
        'ubleipzigbooking.pi_flexform.sheetTemplateOptions' => 'Template-Optionen',
        'ubleipzigbooking.pi_flexform.displayMode.label' => 'Darstellung',
        'ubleipzigbooking.pi_flexform.objectView.label' => 'Objektanzeige',
        'ubleipzigbooking.pi_flexform.adminView.label' => 'Administration',
        'ubleipzigbooking.pi_flexform.includejQuery.label' => 'eigene jQuery-Library verwenden',
        'ubleipzigbooking.pi_flexform.enableQuarterHourBooking.label' => 'viertelstuendliche Buchungen',
        'ubleipzigbooking.pi_flexform.maxBookingsPerDay.label' => 'max. Buchungen pro Tag',
        'ubleipzigbooking.pi_flexform.limitPreviewToDays.label' => 'Begrenze Vorschau auf n Tage',
        'ubleipzigbooking.pi_flexform.limitBookingToDays.label' => 'Begrenze das Buchen auf n Tage in der Zukunft',
        'ubleipzigbooking.pi_flexform.enableFeUserMail.label' => 'Aktiviere FE-User-Email',
        'ubleipzigbooking.pi_flexform.mailSubject.label' => 'Mail Subject',
        'ubleipzigbooking.pi_flexform.mailFromName.label' => 'Mail von Name',
        'ubleipzigbooking.pi_flexform.mailFrom.label' => 'Mail von',
        'ubleipzigbooking.pi_flexform.mailAttachment.label' => 'Mail-Anhang',
        'ubleipzigbooking.pi_flexform.offDutyTimeBegin.label' => 'Begin der Schliesszeit (Tag)',
        'ubleipzigbooking.pi_flexform.offDutyTimeEnd.label' => 'Ende der Schliesszeit (Tag)',
        'ubleipzigbooking.pi_flexform.templateFile.label' => 'Template-Datei',
        'ubleipzigbooking.pi_flexform.cssFile.label' => 'CSS-Datei',
    )
);
?>