<?php

namespace LeipzigUniversityLibrary\Ublbooking\Domain\Model;

use \LeipzigUniversityLibrary\Ublbooking\Library\AbstractEntity;

class Booking extends AbstractEntity {

	/**
	 * frontend user id
	 *
	 * @var integer
	 */
	protected $feUser;

	/**
	 *
	 * @var \LeipzigUniversityLibrary\Ublbooking\Domain\Model\Room
	 */
	protected $room;

	/**
	 * @var string
	 */
	protected $comment;

	/**
	 * timestamp of the booking
	 *
	 * @var integer
	 */
	protected $time;

	/**
	 * DateTime representation of time
	 *
	 * @var \DateTimeImmutable
	 */
	private $dateTime;

	public function __construct($timestamp, $room, $comment = '') {
		if (!$GLOBALS['TSFE']->fe_user->user) throw new \Exception('no user found');
		$this->initializeObject();
		$this->setTime($timestamp);
		$this->setRoom($room);
		$this->setComment($comment);
		$this->setFeUser($GLOBALS['TSFE']->fe_user->user['uid']);

		if ($room->getBookingStorage()) {
			$this->setPid($room->getBookingStorage());
		}
	}

	public function initializeObject() {
		$this->dateTime = new \DateTimeImmutable('now', new \DateTimeZone('Europe/Berlin'));

		parent::initializeObject(); // TODO: Change the autogenerated stub
	}

	public function setTime($value) {
		$this->dateTime = $this->dateTime->setTimestamp($value);
		$this->time = $value;
	}

	public function getDateTime() {
		return $this->dateTime->setTimestamp($this->time);
	}
}